# Generated by Django 2.0 on 2017-12-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundboardFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('uploaded_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SoundboardWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('soundboard_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosounds.SoundboardFile')),
            ],
        ),
    ]
